### ISSUE TITLE
Create a solid documentation

### ISSUE THREAD

**Issue by caiomadeira** [LemonUIbyLemon/LemonUI#107] opened 2023-03-25 19:06 UTC
I see this is the same problem with scripthook

An example of documentation for modders is some like this 
https://wiki.redmodding.org/cyber-engine-tweaks/

**Comment by justalemon** [comment] 2023-03-25 19:09
https://lemonui.itslemonchan.com

It's work in progress due to a DocFx problems that don't allow me to easily create good documentation due to having multiple assemblies with the same functions.

**Comment by justalemon** [comment] 2023-03-25 19:13
Closing as a dupe of #84

**Closed by justalemon** 2023-03-25 19:13 UTC
Labels: priority: p4 not applicable, status: invalid, type: documentation

**Comment by caiomadeira** [comment] 2023-03-25 19:26
Thanks for the answer! I'm studying the project to be able to help in some way :)
